[package]
name = "radicle-keystore"
description = "Abstraction over storage of cryptographic keys within the Radicle stack"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
async-trait = "0.1"
chacha20poly1305 = { version = "0.5.1", default-features = false, features = ["alloc", "chacha20"] }
ed25519-zebra = "2.2"
futures = "0.3"
generic-array = { version = "0.14", features = ["serde"] }
lazy_static = "1"
rpassword = "4.0"
secstr = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
rand = "0.7"
scrypt = { version = "0.4", default-features = false }
thiserror = "1.0"

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
ed25519-dalek = "=1.0.0-pre.4" # lolwut?
rand = { version = "0.7", default-features = false }
sodiumoxide = "0.2"
tempfile = "3"

