[package]
name = "radicle-keystore"
description = "Abstraction over storage of cryptographic keys within the Radicle stack"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
lazy_static = "1.4"
rpassword = "4.0"
secstr = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
sodiumoxide = "0.2"
thiserror = "1.0"

[dev-dependencies]
ed25519-dalek = "1.0.0-pre.3" # lolwut?
rand = "0.7"
tempfile = "3"

