steps:
  - label: "Build, test, doc"
    commands:
      - "ci/build-test"
      - "ci/docs"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-keystore-build@sha256:d9d82db23b399a93501671850621170ccc9455f80f538490ee093285dab6be63"
      DOCKER_FILE: .buildkite/docker/rust/Dockerfile

  - label: "Lint and clip"
    commands:
      - "ci/clippy"
    agents: *build-agent
    env: *build-docker

  - label: "Deny"
    commands:
      - "ci/advisory"
    agents: *build-agent
    env: *build-docker
